config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    # 管理者ログイン
    sessions: 'admin/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    post 'homes/question_import'
    post 'homes/answer_import'

    resources :customers, except: [:new, :create, :destroy]
    resources :questions do
      member do
        resources :answers, only: [:edit, :create, :update, :destroy]
      end
      resources :comments, only: [:create, :destroy]
    end
    resources :ranks
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
    # ログイン・ログアウト(devise)
    get 'customer/sign_in' => 'customer/sessions#new', as: :new_customer_session
    post 'customer/sign_in' => 'customer/sessions#create', as: :customer_session
    delete 'customer/sign_out' => 'customer/sessions#destroy', as: :destroy_customer_session

    # 新規登録(devise)
    get 'customer/sign_up' => 'customer/registrations#new', as: :new_customer_registration
    post 'customer/sign_up' => 'customer/registrations#create', as: :customer_registration

    # パスワード変更(devise)
    get 'customers/edit/password' => 'customer/registrations#edit', as: :edit_customer_registration
    put 'customer/sign_up' => 'customer/registrations#update'
  end

  scope module: :customer do
    root to: 'homes#top'
    #get '/homes/top' => 'homes#top'

    resources :customers, only: [:edit, :update, :show, :index] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      resource :follows, only: [:create, :destroy] do
        get 'followings'
        get 'followers'
      end
    end

    resources :questions do
      collection do
        get "answer_format" => 'questions#answer_format', as: :answer_format
        get 'get_tag_search', defaults: { format: 'json' }
        get "alltags"
      end
      member do
        get "artisan" => 'questions#artisan', as: :artisan
        post "result" => 'questions#result', as: :result
        get 'get_tag_search', defaults: { format: 'json' }
      end
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_customer, only: %i(show edit update)

  def index
    @customers = Customer.all.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    if @customer.update(customer_params)
      redirect_to admin_customer_path(@customer)
    else
      render "edit"
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer
    @customer = Customer.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def customer_params
    params.require(:customer).
      permit(:nickname, :introduction, :email, :rank, :experience_point, :image, :is_valid)
  end
end

app/controllers/customer/comments_controller.rb
class Customer::CommentsController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_question_and_comments!

  def create
    @comment = @question.comments.new(comment_params)
    @comment.customer_id = current_customer.id
    @comment.save
  end

  def destroy
    Comment.find_by(id: params[:id]).destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question_and_comments!
    @question = Question.find(params[:question_id])
    @comments = @question.comments.includes(:customer).order(id: "desc").page(params[:page]).per(10)
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/customer/confirmations_controller.rb
# frozen_string_literal: true

class Customer::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customer/customers_controller.rb
class Customer::CustomersController < ApplicationController
  before_action :authenticate_customer!, except: [:index, :show]

  def index
    @customers = Customer.where(is_valid: true).order(rank: "desc").page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
    if customer_signed_in?
      @questions = @customer.questions.
        includes(:tags, :favorites, :results).page(params[:page]).per(10)
    else
      @questions = @customer.questions.includes(:tags).page(params[:page]).per(10)
    end
  end

  def edit
    @customer = Customer.find(params[:id])
    if @customer != current_customer
      redirect_to customer_path(@customer)
    end
  end

  def update
    if current_customer.update(customer_params)
      redirect_to customer_path(current_customer),
      notice: "Your account has been updated successfully."
    else
      render :edit
    end
  end

  def unsubscribe
  end

  def withdraw
    current_customer.update_attribute(:is_valid, false)
    reset_session
    flash[:alert] = '退会しました。'
    redirect_to root_path
  end

  private

  def customer_params
    params.require(:customer).permit(:nickname, :email, :introduction, :image)
  end
end

app/controllers/customer/favorites_controller.rb
class Customer::FavoritesController < ApplicationController
  before_action :authenticate_customer!
  before_action :set_question!

  def create
    favorite = current_customer.favorites.new(question_id: @question.id)
    favorite.save
  end

  def destroy
    favorite = current_customer.favorites.find_by(question_id: @question.id)
    favorite.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question!
    @question = Question.find(params[:question_id])
  end
end

app/controllers/customer/follows_controller.rb
class Customer::FollowsController < ApplicationController
  before_action :set_customer!
  before_action :authenticate_customer!, only: [:create, :destroy]

  # フォローする人：current_customer.id, フォローされる人：params[:customer_id]
  def create
    follow = Follow.new(following_id: current_customer.id, followed_id: @customer.id)
    follow.save
    # artisanのresult画面から来たときだけ非同期
    unless URI(request.referer.to_s).path.include?("/artisan")
      redirect_back(fallback_location: root_path)
    end
  end

  def followings
  end

  def followers
  end

  def destroy
    follow = current_customer.following.find_by(followed_id: @customer.id)
    follow.destroy!
    unless URI(request.referer.to_s).path.include?("/artisan")
      redirect_back(fallback_location: root_path)
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_customer!
    @customer = Customer.find(params[:customer_id])
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    if customer_signed_in?
      @questions = Question.includes(:tags, :favorites, :results).
        order(id: "desc").page(params[:page]).per(3)
    else
      @questions = Question.includes(:tags).order(id: "desc").page(params[:page]).per(3)
    end
  end
end

app/controllers/customer/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customer::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customer/passwords_controller.rb
# frozen_string_literal: true

class Customer::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customer/questions_controller.rb
class Customer::QuestionsController < ApplicationController
  before_action :set_question!, only: %i(show edit update destroy artisan result)
  before_action :authenticate_customer!,
  except: [:index, :show, :artisan, :result, :search, :alltags]
  before_action :ensure_correct_customer!, only: [:show, :edit, :update, :destroy]
  before_action :set_format!, only: [:new, :create, :edit, :update, :answer_format]
  before_action :initialize_answer, only: [:new, :answer_format]

  # GET /questions
  def index
    @content = params[:content]
    @column = params[:column]
    if customer_signed_in?
      @questions = Question.includes(:tags, :favorites, :results).
        search(@content, @column).page(params[:page]).per(10)
    else
      @questions = Question.includes(:tags).search(@content, @column).page(params[:page]).per(10)
    end
    @tags = Question.tag_counts_on(:tags).most_used(10).order('count DESC')
  end

  # GET /questions/1
  def show
  end

  # GET /questions/new
  def new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  def create
    @question = Question.new(question_params)

    if @question.save
      # AI
      if params[:question][:auto_tag_image] && (params[:question][:question_image] != "{}")
        @question.tag_list += Vision.get_image_data(@question.question_image)
      end
      if params[:question][:auto_tag_sentence]
        @question.tag_list += Language.get_entity(@question.sentence)
      end

      # タグは10こまで
      if @question.tag_list.size > ENV["MAX_TAGS"].to_i
        @question.tag_list.pop(@question.tag_list.size - ENV["MAX_TAGS"].to_i)
        flash[:alert] = "タグは10個までです。11個目以降は削除されました。"
      end

      @question.save

      redirect_to @question, notice: "Question was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /questions/1
  def update
    if @question.update(question_params)

      if params[:question][:auto_tag_image]
        @question.tag_list += Vision.get_image_data(@question.question_image)
      end
      if params[:question][:auto_tag_sentence]
        @question.tag_list += Language.get_entity(@question.sentence)
      end

      # タグは10こまで
      if @question.tag_list.size > ENV["MAX_TAGS"].to_i
        @question.tag_list.pop(@question.tag_list.size - ENV["MAX_TAGS"].to_i)
        flash[:alert] = "タグは10個までです。11個目以降は削除されました。"
      end

      @question.save

      redirect_to @question, notice: "Question was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /questions/1
  def destroy
    @question.destroy
    redirect_to questions_url, notice: "Question was successfully destroyed."
  end

  def answer_format
  end

  def alltags
    @tags = Question.tag_counts_on(:tags).order('count DESC')
  end

  def artisan
    impressionist(@question, nil, unique: [:impressionable_id, :ip_address])
    @tags = @question.tag_counts_on(:tags).order('count DESC')
    @comments = @question.comments.includes(:customer).order(id: "desc").page(params[:page]).per(10)
  end

  # too fat
  def result
    # 回答セット
    @your_answers = params[:your_answers] || []
    @correct = false
    @rankup = false

    # 回答判定
    if @question.format == "writing"
      if @question.correct_answers.where(content: "#{@your_answers}").exists?
        @correct = true
      end
    else
      @your_answers.map! { |x| x.to_i }
      if @question.correct_answers.ids == @your_answers
        @correct = true
      end
    end

    # 回答数更新
    if @correct
      @question.correct_answered_time += 1
    end
    @question.answered_time += 1
    @question.save

    # ユーザ登録済みなら、クリア状況と経験値更新
    if customer_signed_in?
      # クリアランプ更新
      if @question.result?(current_customer)
        result = current_customer.results.find_by(question_id: @question.id)
      else
        result = current_customer.results.new(question_id: @question.id)
      end
      result.trial_count += 1
      if @correct
        result.is_cleared = true
      end
      result.save

      # 解く側の経験値
      if @correct
        current_customer.experience_point += ENV["CORRECT_EXP"].to_i
      else
        current_customer.experience_point += ENV["INCORRECT_EXP"].to_i
      end
      current_customer.save
      @rankup = current_customer.rankup?

      # 解かれた側の経験値
      if current_customer != @question.customer
        @question.customer.experience_point += ENV["ANSWERED_EXP"].to_i
        @question.customer.save
        @question.customer.rankup?
      end
    end
  end

  def get_tag_search
    @tags = Question.tag_counts_on(:tags).where('name LIKE(?)', "%#{params[:key]}%")
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_question!
    @question = Question.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def question_params
    params.require(:question).permit(
      :customer_id,
      :title,
      :sentence,
      :format,
      :explanation,
      :question_image,
      :answer_image,
      :answered_time,
      :correct_answered_time,
      :tag_list,
      answers_attributes: [:id, :content, :is_correct, :order, :_destroy]
    )
  end

  def ensure_correct_customer!
    @question = Question.find(params[:id])
    unless @question.customer == current_customer
      redirect_to artisan_question_path(@question)
    end
  end

  def set_format!
    @formats = Question.formats_i18n
  end

  def initialize_answer
    @question = Question.new
    if params[:format]
      @question.format = params[:format]
    else
      # 最初は○×をセット
      @question.format = "bool"
    end
    case @question.format
    when "bool"
      @question.answers.build(content: "○", is_correct: true)
      @question.answers.build(content: "×", is_correct: false)
    else
      @question.answers.build(is_correct: true)
    end
  end
end

app/controllers/customer/registrations_controller.rb
# frozen_string_literal: true

class Customer::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customer/sessions_controller.rb
# frozen_string_literal: true

class Customer::SessionsController < Devise::SessionsController
  before_action :check_customer_status, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # 退会ステータスを確認
  def check_customer_status
    @customer = Customer.find_by(nickname: params[:customer][:nickname])
    return if !@customer
    if @customer.valid_password?(params[:customer][:password]) && (@customer.is_valid == false)
      flash[:alert] = "このアカウントは退会済みです。"
      redirect_to new_customer_session_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customer/comments_helper.rb
module Customer::CommentsHelper
end

app/helpers/customer/customers_helper.rb
module Customer::CustomersHelper
end

app/helpers/customer/favorites_helper.rb
module Customer::FavoritesHelper
end

app/helpers/customer/follows_helper.rb
module Customer::FollowsHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/views/customer/customers/_index.html.erb
<% customers.each do |customer| %>
  <div class="card bg-light mb-3 shadow">
    <div class="row no-gutters">
      <div class="col-md-2 card-header bg-warning d-flex justify-content-center">
        <div class="">
          <%= attachment_image_tag customer, :image, :fill, 100, 100, format: 'jpg', fallback: "no_image.jpg", size:'100x100' %>
        </div>
      </div>
      <div class="col-md-10">
        <div class="card-header bg-warning d-flex justify-content-between align-items-end">
          <div class="d-flex justify-content-start align-items-end">
            <div class="">
              <p class="card-title">Rank:<%= customer.rank %></p>
            </div>
            <div class="mx-3">
              <%= link_to customer_path(customer) do %>
                <h4 class="card-title"><%= customer.nickname %></h4>
              <% end %>
            </div>
          </div>
          <div class="d-flex justify-content-end align-items-end">
            <div class=""><p class="card-title">投稿数:<%= customer.questions_count %></p></div>
            <div class="follow-btn-<%= customer.id %> mx-1"><%= render "customer/follows/follow", customer: customer %></div>
            <div class="mx-1"><i class="fas fa-sign-out-alt fa-lg text-danger"></i> <%= link_to customer.following_count, followings_customer_follows_path(customer), class:"btn btn-outline-danger" %></div>
            <div class="mx-1"><i class="fas fa-sign-in-alt fa-lg text-primary"></i> <%= link_to customer.followed_count, followers_customer_follows_path(customer), class:"btn btn-outline-primary" %></div>
          </div>
        </div>
        <div class="card-body">
          <%= customer.introduction %>
        </div>
      </div>
    </div>
  </div>
<% end %>
<% paginate customers %>

app/views/customer/customers/edit.html.erb
<h1>Profile Edit</h1>
<%= form_with model: current_customer, local: true do |form| %>
  <% if current_customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(current_customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% current_customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card bg-warning border-dark mb-3 shadow">
    <div class="row no-gutters">
      <div class="col-md-5">
        <div class="card-header d-flex flex-column align-items-center">
          <div><%= attachment_image_tag current_customer, :image, :fill, 120, 120, format: 'jpg', fallback: "no_image.jpg", size:'120x120' %></div>
        </div>
        <div class="card-body">
          <%= form.attachment_field :image, placeholder: "プロフィール画像" %>
        </div>
      </div>
      <div class="col-md-7">
        <div class="card-header d-flex justify-content-between">
          <div class="d-flex justify-content-start align-items-center">
            <div class="field">
              <%= form.text_field :nickname, placeholder:"nickname" %>
            </div>
            <div class="mx-3">Rank:<%= current_customer.rank %></div>
          </div>
          <div class="d-flex justify-content-end align-items-center">
            <div class="mx-3">投稿数：<%= current_customer.questions_count %></div>
            <div class="">
              <i class="fas fa-sign-out-alt fa-lg text-danger mx-1"></i><span class:"btn btn-outline-danger"><%= current_customer.following_count %></span>
              <i class="fas fa-sign-in-alt fa-lg text-primary mx-1"></i><span class:"btn btn-outline-primary"><%= current_customer.followed_count %></span>
            </div>
          </div>
        </div>
        <div class="card-body bg-light text-dark d-flex justify-content-start">
          <div>総経験値：<%= current_customer.experience_point %></div>
          <div class="mx-3">次まで：<%= current_customer.next_rank_exp %></div>
        </div>
        <div class="card-body bg-light text-dark d-flex justify-content-start">
          <div class="mr-3">登録日：<%= current_customer.created_at.strftime('%Y/%m/%d') %></div>
          <div class="field">
            <%= form.email_field :email, placeholder:"email" %>
          </div>
        </div>
        <div class="card-body bg-light text-dark d-flex justify-content-between align-items-end">
          <div class="field">
            <%= form.text_area :introduction, size: "50x3", placeholder:"introduction" %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-success" %>
  </div>

<% end %>

<%= link_to "Back", customer_path(current_customer), class: 'fas fa-user nav-link' %>

<h1 class="mt-5">Or More?</h1>

<div class="actions">
  <%= link_to "パスワードを変更する", edit_customer_registration_path(current_customer), class:"btn btn-info" %>
</div>

<div class="actions">
  <%= link_to "退会する", unsubscribe_customers_path, class:"btn btn-danger" %>
</div>

app/views/customer/customers/index.html.erb
<h1>Top Ranking</h1>
<%= render "index", customers: @customers %>

app/views/customer/customers/show.html.erb
<h1>Profile</h1>
<div class="card bg-warning border-dark mb-3 shadow">
  <div class="row no-gutters">
    <div class="col-md-3 card-header d-flex justify-content-center align-items-center">
        <div><%= attachment_image_tag @customer, :image, :fill, 150, 150, format: 'jpg', fallback: "no_image.jpg", size:'150x150' %></div>
    </div>
    <div class="col-md-9">
      <div class="card-header d-flex justify-content-between">
        <div class="d-flex justify-content-start align-items-center">
          <h4 class=""><%= @customer.nickname %></h4>
          <div class="mx-3">Rank:<%= @customer.rank %></div>
        </div>
        <div class="d-flex justify-content-end align-items-center">
          <div class="mx-3">投稿数：<%= @customer.questions_count %></div>
          <div class="follow-btn-<%= @customer.id %> mx-1"><%= render "customer/follows/follow", customer: @customer %></div>
          <div class="">
            <i class="fas fa-sign-out-alt fa-lg text-danger mx-1">フォロー<%= link_to @customer.following_count, followings_customer_follows_path(@customer), class:"btn btn-outline-danger" %></i>
            <i class="fas fa-sign-in-alt fa-lg text-primary mx-1">フォロワー<%= link_to @customer.followed_count, followers_customer_follows_path(@customer), class:"btn btn-outline-primary" %></i>
          </div>
        </div>
      </div>
      <div class="card-body bg-light text-dark d-flex justify-content-between align-items-end">
        <div><%= @customer.introduction %></div>
      </div>
      <div class="card-body bg-light text-dark d-flex justify-content-start">
        <% if customer_signed_in? && @customer.id == current_customer.id %>
          <div>総経験値：<%= @customer.experience_point %></div>
          <div class="mx-3">次まで：<%= @customer.next_rank_exp %></div>
        <% end %>
      </div>
      <div class="card-footer bg-light text-dark d-flex justify-content-start">
        <div class="mr-3">登録日：<%= @customer.created_at.strftime('%Y/%m/%d') %></div>
        <% if customer_signed_in? && @customer.id == current_customer.id %>
          <div><%= @customer.email %></div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if customer_signed_in? && @customer.id == current_customer.id %>
  <%= link_to 'Edit', edit_customer_path(@customer), class: 'fas fa-user-edit nav-link' %>
<% end %>

<h1 class="mt-5">Questions</h1>

<div class="">
  <%= render "customer/questions/list", questions: @questions %>
</div>

app/views/customer/customers/unsubscribe.html.erb
<div class="row justify-content-center">
  <div class="col-sm-10 border shadow p-3 rounded bg-light m-3 text-center">
    <h3><strong>本当に退会しますか？</strong></h3>
    <p>
      退会すると、会員登録情報や<br>
      これまでの購入記録が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。<br>
    </p>
    <div class="unsubscribe">
      <%= link_to "退会しない", customer_path(current_customer), class:"btn btn-success" %>
      <%= link_to "退会する", withdraw_customers_path, method: :patch, class:"btn btn-danger" %>
    </div>
  </div>
</div>