config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    # 管理者ログイン
    sessions: 'admin/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    post 'homes/question_import'
    post 'homes/answer_import'

    resources :customers, except: [:new, :create, :destroy]
    resources :questions do
      member do
        resources :answers, only: [:edit, :create, :update, :destroy]
      end
      resources :comments, only: [:create, :destroy]
    end
    resources :ranks
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
    # ログイン・ログアウト(devise)
    get 'customer/sign_in' => 'customer/sessions#new', as: :new_customer_session
    post 'customer/sign_in' => 'customer/sessions#create', as: :customer_session
    delete 'customer/sign_out' => 'customer/sessions#destroy', as: :destroy_customer_session

    # 新規登録(devise)
    get 'customer/sign_up' => 'customer/registrations#new', as: :new_customer_registration
    post 'customer/sign_up' => 'customer/registrations#create', as: :customer_registration

    # パスワード変更(devise)
    get 'customers/edit/password' => 'customer/registrations#edit', as: :edit_customer_registration
    put 'customer/sign_up' => 'customer/registrations#update'
  end

  scope module: :customer do
    root to: 'homes#top'
    #get '/homes/top' => 'homes#top'

    resources :customers, only: [:edit, :update, :show, :index] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      resource :follows, only: [:create, :destroy] do
        get 'followings'
        get 'followers'
      end
    end

    resources :questions do
      collection do
        get "answer_format" => 'questions#answer_format', as: :answer_format
        get 'get_tag_search', defaults: { format: 'json' }
        get "alltags"
      end
      member do
        get "artisan" => 'questions#artisan', as: :artisan
        post "result" => 'questions#result', as: :result
        get 'get_tag_search', defaults: { format: 'json' }
      end
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/views/layouts/admin/_footer.html.erb
<footer class="footer bg-dark text-light">
  <div class="copyright">
    &copy; A.Ichikawa via DMM WEBCAMP
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header class="header">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <h1 class="site_logo">
      <a href="/admin" class="navbar-brand">
        Question Artisan -Admin Mode-
      </a>
    </h1>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li><%= link_to 'adminログアウト', destroy_admin_session_path, method: :delete, class: 'fas fa-sign-out-alt nav-link text-light' %></li>
          <li><%= link_to 'ランク', admin_ranks_path, class: 'fas fa-award nav-link text-light' %></li>
          <li><%= link_to 'ユーザー一覧', admin_customers_path, class: 'fas fa-user nav-link text-light' %></li>
          <li><%= link_to '設問一覧', admin_questions_path, class: 'fas fa-question nav-link text-light' %></li>
        <% else %>
          <li><%= link_to 'adminログイン', new_admin_session_path, class: 'fas fa-sign-in-alt nav-link text-light' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/admin/_main.html.erb
<div id="admin_bg">
  <div class="admin_textarea">
    <div class="container">
      <p id="notice"><%= notice %></p>
      <p id="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </div>
</div>