config/routes.rb
Rails.application.routes.draw do
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    # 管理者ログイン
    sessions: 'admin/sessions',
  }

  namespace :admin do
    root to: 'homes#top'
    post 'homes/question_import'
    post 'homes/answer_import'

    resources :customers, except: [:new, :create, :destroy]
    resources :questions do
      member do
        resources :answers, only: [:edit, :create, :update, :destroy]
      end
      resources :comments, only: [:create, :destroy]
    end
    resources :ranks
  end

  devise_for :customers, skip: :all
  devise_scope :customer do
    # ログイン・ログアウト(devise)
    get 'customer/sign_in' => 'customer/sessions#new', as: :new_customer_session
    post 'customer/sign_in' => 'customer/sessions#create', as: :customer_session
    delete 'customer/sign_out' => 'customer/sessions#destroy', as: :destroy_customer_session

    # 新規登録(devise)
    get 'customer/sign_up' => 'customer/registrations#new', as: :new_customer_registration
    post 'customer/sign_up' => 'customer/registrations#create', as: :customer_registration

    # パスワード変更(devise)
    get 'customers/edit/password' => 'customer/registrations#edit', as: :edit_customer_registration
    put 'customer/sign_up' => 'customer/registrations#update'
  end

  scope module: :customer do
    root to: 'homes#top'
    #get '/homes/top' => 'homes#top'

    resources :customers, only: [:edit, :update, :show, :index] do
      collection do
        get 'unsubscribe'
        patch 'withdraw'
      end
      resource :follows, only: [:create, :destroy] do
        get 'followings'
        get 'followers'
      end
    end

    resources :questions do
      collection do
        get "answer_format" => 'questions#answer_format', as: :answer_format
        get 'get_tag_search', defaults: { format: 'json' }
        get "alltags"
      end
      member do
        get "artisan" => 'questions#artisan', as: :artisan
        post "result" => 'questions#result', as: :result
        get 'get_tag_search', defaults: { format: 'json' }
      end
      resources :comments, only: [:create, :destroy]
      resource :favorites, only: [:create, :destroy]
    end
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!

  def top
    @questions = Question.all
    @customers = Customer.where(is_valid: true)
    # csv出力用
    respond_to do |format|
      format.html
      format.csv do |csv|
        if params[:type] == "question"
          question_export(@questions)
        elsif params[:type] == "answer"
          @answers = Answer.all
          answer_export(@answers)
        end
      end
    end
  end

  # csv export
  def question_export(questions)
    csv_data = CSV.generate do |csv|
      header = %w(id customer_id title sentence format explanation)
      csv << header
      questions.each do |question|
        # customer_id = admin
        values = [
          question.id,
          0,
          question.title,
          question.sentence,
          question.format,
          question.explanation,
        ]
        csv << values
      end
    end
    send_data(csv_data, filename: "questions.csv")
  end

  def answer_export(answers)
    csv_data = CSV.generate do |csv|
      header = %w(id question_id content is_correct)
      csv << header
      answers.each do |answer|
        values = [answer.id, answer.question_id, answer.content, answer.is_correct]
        csv << values
      end
    end
    send_data(csv_data, filename: "answers.csv")
  end

  # csv import
  def question_import
    Question.import(params[:file])
    redirect_to admin_root_path, notice: "Questions were successfully imported."
  end

  # csv import
  def answer_import
    Answer.import(params[:file])
    redirect_to admin_root_path, notice: "Answers wewe successfully imported."
  end
end

app/controllers/customer/homes_controller.rb
class Customer::HomesController < ApplicationController
  def top
    if customer_signed_in?
      @questions = Question.includes(:tags, :favorites, :results).
        order(id: "desc").page(params[:page]).per(3)
    else
      @questions = Question.includes(:tags).order(id: "desc").page(params[:page]).per(3)
    end
  end
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/customer/homes_helper.rb
module Customer::HomesHelper
end

app/views/admin/homes/top.html.erb
<h1>Question Artisan -Admin Mode-</h1>

<div class="row justify-content-center h-100">
  <div class="col-sm-5 border shadow p-3 rounded bg-light m-3">
    <h3 class="mb-4">問題数</h3>
    <%= @questions.size %>
  </div>
  <div class="col-sm-5 border shadow p-3 rounded bg-light m-3">
    <h3 class="mb-4">有効ユーザー数</h3>
    <%= @customers.size %>
  </div>
</div>

<div class="row justify-content-center h-100">
  <div class="col-sm-5 border shadow p-3 rounded bg-light m-3">
    <h3 class="mb-4">Question import/export</h3>
    <%= form_with url: admin_homes_question_import_path, html: { method: :post, multipart: true } do |f| %>
      <%= f.file_field :file %>
      <div class="my-3">
        <%= f.submit "import questions csv", class:"btn btn-primary" %>
      </div>
    <% end %>
    <br>
    <%= link_to "export Q csv", admin_root_path(format: :csv, :type => "question"), class:"btn btn-danger" %>
  </div>

  <div class="col-sm-5 border shadow p-3 rounded bg-light m-3">
    <h3 class="mb-4">Answer import/export</h3>
    <%= form_with url: admin_homes_answer_import_path, html: { method: :post, multipart: true } do |f| %>
      <%= f.file_field :file %>
      <div class="my-3">
        <%= f.submit "import answers csv", class:"btn btn-primary" %>
      </div>
    <% end %>
    <br>
    <%= link_to "export A csv", admin_root_path(format: :csv, :type => "answer"), class:"btn btn-danger" %>
  </div>
</div>